name: CI

on: workflow_dispatch

jobs:
  linux:
    name: Build linux binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: ./build.sh
      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: ampm linux binaries
          if-no-files-found: error
          path: |
            dist/ampm.tar.gz
            dist/get_ampm.sh